Update ref-update

diff --git a/ref-update b/ref-update
--- a/ref-update
+++ b/ref-update
@@ -58,8 +58,8 @@ fi
 
 
 ## Check for Jira issue in footer
-if [ "$(git -c pager.show=false show --no-patch --pretty=format:%B $NEWREV | egrep -q '^(Issue: AHML[A-Z]+\-[0-9]+,?)+$'; echo $?)" -gt "0" ]; then
-    echo "Commit $NEWREV Missing Jira key in message commit footer. Expected format: 'Issue: AHMLXXX-1234'"
+if [ "$(git -c pager.show=false show --no-patch --pretty=format:%B $NEWREV | egrep -q '^(Issue: AL[A-Z]+\-[0-9]+,?)+$'; echo $?)" -gt "0" ]; then
+    echo "Commit $NEWREV Missing Jira key in message commit footer. Expected format: 'Issue: AMXXX-1234'"
     echo "Use git commit --amend to add missing footer, then try again."
     exit 1
 fi
